
[BasicMastery]
Name = "Basic Mastery"
Icon = "nv_basic"
Target = "Passive"
MaxLevel = 8

[FirstAid]
Name = "First Aid"
Icon = "nv_firstaid"
Target = "Self"
MaxLevel = 1
SpCost = [10]

[Bash]
Icon = "sm_bash"
Target = "Enemy"
MaxLevel = 10
SpCost = [8,8,8,8,8,15,15,15,15,15]
AdjustableLevel = true

[Endure]
Icon = "sm_endure"
Target = "Self"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[IncreasedHPRecovery]
Name = "Improved HP Recovery"
Icon = "sm_recovery"
MaxLevel = 10
Target = "Passive"

[MagnumBreak]
Name = "Magnum Break"
Icon = "sm_magnum"
Target = "Self"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[Provoke]
Icon = "sm_provoke"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[SwordMastery]
Name = "Sword Mastery"
Icon = "sm_sword"
Target = "Passive"
MaxLevel = 10

[TwoHandSwordMastery]
Name = "Two-Hand Sword Mastery"
Icon = "sm_twohand"
Target = "Passive"
MaxLevel = 10

[IncreaseSPRecovery]
Name = "Improved Spiritual Recovery"
Icon = "mg_srecovery"
Target = "Passive"
MaxLevel = 10

[FireBolt]
Name = "Fire Bolt"
Icon = "mg_firebolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[ColdBolt]
Name = "Cold Bolt"
Icon = "mg_coldbolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[FireBall]
Name = "Fire Ball"
Icon = "mg_fireball"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[FireWall]
Name = "Fire Wall"
Icon = "mg_firewall"
Target = "Ground"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[FrostDriver]
Name = "Frost Diver"
Icon = "mg_frostdiver"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[LightningBolt]
Name = "Lightning Bolt"
Icon = "mg_lightningbolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[SoulStrike]
Name = "Soul Strike"
Icon = "mg_soulstrike"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[ThunderStorm]
Name = "Thunderstorm"
Icon = "mg_thunderstorm"
Target = "Ground"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[SafetyWall]
Name = "Safety Wall"
Icon = "mg_safetywall"
Target = "Ground"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[DoubleStrafe]
Name = "Double Strafe"
Icon = "ac_double"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[ChargeArrow]
Name = "Charge Arrow"
Icon = "ac_chargearrow"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[ArrowShower]
Name = "Arrow Shower"
Icon = "ac_shower"
Target = "Ground"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[ImproveConcentration]
Name = "Improve Concentration"
Icon = "ac_concentration"
Target = "Self"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[Heal]
Icon = "al_heal"
Target = "Ally"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[IncreaseAgility]
Name = "Increase Agility"
Icon = "al_incagi"
Target = "Ally"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[Blessing]
Icon = "al_blessing"
Target = "Ally"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[DoubleAttack]
Name = "Double Attack"
Icon = "tf_double"
Target = "Passive"
MaxLevel = 10

[Envenom]
Icon = "th_poison"
Target = "Enemy"
SpCost = [1,2,3,4,5,6,7,8,9,10]
MaxLevel = 10

[Mammonite]
Icon = "mc_mammonite"
Target = "Enemy"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]
AdjustableLevel = true

[PushCart]
Name = "Push Cart"
Icon = "mc_pushcart"
Target = "Passive"
MaxLevel = 1

#Other skills
[TwoHandQuicken]
Name = "Two-Hand Quicken"
Icon = "kn_twohandquicken"
Target = "Self"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[HammerFall]
Name = "Hammer Fall"
Icon = "bs_hammerfall"
Target = "Ground"
MaxLevel = 5
SpCost = [1,2,3,4,5,6,7,8,9,10]

#Monster Skills
[CallMinion]
Name = "Call Minion"
[GrandThunderstorm]
Name = "Grand Thunderstorm"

[SelfDestruct]
Name = "Self Destruct"

[PowerUp]
Name = "Power UP"

[NoCast]
#use when you want the enemy to trigger something without the player knowing
#use None instead if you want the skill flash to still show