
[Novice]
JobRank = 0
[Novice.SkillTree]
BasicMastery = []
FirstAid = [["BasicMastery", 2]]

[Swordsman]
JobRank = 1
Extends = "Novice"
[Swordsman.SkillTree]
SwordMastery = []
TwoHandSwordMastery = [["SwordMastery", 1]]
IncreasedHPRecovery = []
Bash = []
MagnumBreak = [["Bash", 5]]
Provoke = []
Endure = [["Provoke", 5]]
ChargeAttack = [["Bash", 7], ["MagnumBreak", 3]]
#TwoHandQuicken = [["TwoHandSwordMastery", 10], ["Endure", 5]] #just for testing

[Archer]
JobRank = 1
Extends = "Novice"
[Archer.SkillTree]
OwlEye = []
VultureEye = [["OwlEye", 3]]
DoubleStrafe = []
ArrowShower = [["DoubleStrafe", 10]]
ImproveConcentration = [["VultureEye", 1]]
ChargeArrow = [["OwlEye", 5], ["VultureEye", 5]]
#BeastBane = [["OwlEye", 10]]
#AnkleSnare = [["ImproveConcentration", 10], ["BeastBane", 10]]

[Mage]
JobRank = 1
Extends = "Novice"
[Mage.SkillTree]
IncreaseSPRecovery = []
FireBolt = []
FireBall = [["FireBolt", 4]]
FireWall = [["Sight", 1], ["FireBall", 5]]
LightningBolt = []
ThunderStorm = [["LightningBolt", 4]]
ColdBolt = []
FrostDiver = [["ColdBolt", 5]]
Sight = []
NapalmBeat = []
SoulStrike = [["NapalmBeat", 4]]
SafetyWall = [["NapalmBeat", 7], ["SoulStrike", 5]]
StoneCurse = []
EnergyCoat = [["FireBolt", 3], ["ColdBolt", 3], ["LightningBolt", 3]]

[Acolyte]
JobRank = 1
Extends = "Novice"
[Acolyte.SkillTree]
DivineProtection = []
DemonBane = [["DivineProtection", 1]]
Heal = []
Angelus = [["DivineProtection", 3]]
Blessing = [["DivineProtection", 5]]
IncreaseAgility = [["Heal", 3]]
DecreaseAgility = [["IncreaseAgility", 1]]
Cure = [["Heal", 2]]
Ruwach = []
Teleport = [["Ruwach", 1]]
Return = [["Teleport", 1]]
WarpPortal = [["Return", 1]]
Pneuma = [["WarpPortal", 4]]
HolyLight = [["DemonBane", 1]]
SignumCrusis = [["DemonBane", 3]]
AquaBenedicta = []

[Thief]
JobRank = 1
Extends = "Novice"
[Thief.SkillTree]
DoubleAttack = []
ImproveDodge = []
Envenom = []
Detoxify = [["Envenom", 3]]
Steal = []
Hiding = [["Steal", 5]]
#SandAttack = [["Envenom", 5]]
BackSlide = [["ImproveDodge",5]]
#FindStone = []

[Merchant]
JobRank = 1
Extends = "Novice"
[Merchant.SkillTree]
EnlargeWeightLimit = []
Discount = [["EnlargeWeightLimit",3]]
Overcharge = [["Discount",3]]
PushCart = [["EnlargeWeightLimit",5]]
Vending = [["PushCart",3]]
ItemAppraisal = [["Discount",5]]
Mammonite = []
CrazyUproar = [["Mammonite", 3], ["ItemAppraisal", 1]]
CartRevolution = [["PushCart", 10], ["CrazyUproar", 1]]

[Knight]
JobRank = 2
Extends = "Swordsman"
[Knight.SkillTree]
CounterAttack = [["TwoHandSwordMastery",1]]
TwoHandQuicken = [["TwoHandSwordMastery",1]]
BowlingBash = [["TwoHandSwordMastery",5],["Bash",10],["CounterAttack",5],["TwoHandQuicken",10]]
PecoPecoRiding = [["Endure",1]]
CavalierMastery = [["PecoPecoRiding",1]]
SpearMastery = []
Pierce = [["SpearMastery",1]]
SpearBoomerang = [["Pierce",3]]
SpearStab = [["Pierce",5]]
BrandishSpear = [["PecoPecoRiding",1],["SpearStab",3]]

[Wizard]
JobRank = 2
Extends = "Mage"
[Wizard.SkillTree]
Sightrasher = [["Sight",1],["LightningBolt",1]]
MeteorStorm = [["Sightrasher",2],["ThunderStorm",1]]
JupitelThunder = [["LightningBolt",1],["NapalmBeat",1]]
LordOfVermilion = [["ThunderStorm",1],["JupitelThunder",5]]
WaterBall = [["LightningBolt",1],["ColdBolt",1]]
StormGust = [["JupitelThunder",3],["FrostDiver",1]]
IceWall = [["FrostDiver",1],["StoneCurse",1]]
FrostNova = [["IceWall", 1]]
EarthSpike = [["StoneCurse", 1]]
HeavensDrive = [["EarthSpike", 3]]
Quagmire = [["HeavensDrive",1]]

[Priest]
JobRank = 2
Extends = "Acolyte"
[Priest.SkillTree]
IncreaseSPRecovery = []
MaceMastery = []
Magnificat = []
KyrieEleison = [["Angelus",2]]
Gloria = [["KyrieEleison",4],["Magnificat",3]]
StatusRecovery = []
Resurrection = [["IncreaseSPRecovery",4],["StatusRecovery",1]]
ImpositioManus = []
Aspersio = [["AquaBenedicta",1],["ImpositioManus",3]]
Suffragium = [["ImpositioManus",2]]
Sanctuary = [["Heal",1]]
SafetyWall = [["Aspersio",4],["Sanctuary",3]]
LexDivina = [["Ruwach",1]]
LexAeterna = [["LexDivina",5]]
TurnUndead = [["LexDivina",3],["Resurrection",1]]
MagnusExorcismus = [["SafetyWall",1],["LexAeterna",1],["TurnUndead",3]]

[Hunter]
JobRank = 2
Extends = "Archer"
[Hunter.SkillTree]
BeastBane = []
FalconMastery = [["BeastBane", 1]]
BlitzBeat = [["FalconMastery", 1]]
SteelCrow = [["BlitzBeat", 5]]
Detect = [["ImproveConcentration",1],["FalconMastery",1]]
LandMine = []
RemoveTrap = [["LandMine", 1]]
SpringTrap = [["FalconMastery", 1],["RemoveTrap", 1]]
SkidTrap = []
AnkleSnare = [["SkidTrap",1]]
ShockwaveTrap = [["AnkleSnare",1]]
TalkieBox = [["ShockwaveTrap",1]]
Flasher = [["SkidTrap",1]]
Sandman = [["Flasher",1]]
FreezingTrap = [["Flasher",1]]
BlastMine = [["LandMine",1],["Sandman",1],["FreezingTrap",1]]
ClaymoreTrap = [["ShockwaveTrap",1],["BlastMine",1]]

[Assassin]
JobRank = 2
Extends = "Thief"
[Assassin.SkillTree]
RightHandMastery = []
LeftHandMastery = [["RightHandMastery",2]]
KatarMastery = []
SonicBlow = [["KatarMastery",4]]
Cloaking = [["Hiding",2]]
Grimtooth = [["SonicBlow",5],["Cloaking",2]]
EnchantPoison = [["Envenom",1]]
PoisonReact = [["EnchantPoison",3]]
VenomDust = [["EnchantPoison",5]]
VenomSplasher = [["PoisonReact",5],["VenomDust",5]]

[Blacksmith]
JobRank = 2
Extends = "Merchant"
[Blacksmith.SkillTree]
HiltBinding = []
WeaponryResearch = [["HiltBinding",1]]
HammerFall = []
AdrenalineRush = [["HammerFall",2]]
WeaponPerfection = [["WeaponryResearch",2],["AdrenalineRush",2]]
PowerThrust = [["AdrenalineRush",3]]
MaximizePower = [["WeaponPerfection",3],["PowerThrust",2]]