#
#Status Effects!
#
#Type = "Buff" or "Debuff". Used for targeting certain effects as well as positioning on the UI.
#CanDispel = if the buff can be lost by either dying or being targeted by dispel.
#CanDisable = if the player themselves can remove the status effect by right clicking the buff.

#----------------------------------
# General Negative Status Effects
#----------------------------------

[Curse]
Type = "Debuff"
Icon = "hl_curse"

[Stun]
Type = "Debuff"
Icon = "bd_stun"

[Sleep]
Type = "Debuff"
Icon = "bd_sleep"

[Frozen]
Type = "Debuff"
Icon = "bd_freezing"

[Blind]
Type = "Debuff"
Icon = "hl_blind"

[Silence]
Type = "Debuff"
Icon = "hl_silence"

[Confusion]
Type = "Debuff"
Icon = "hl_confusion"

[Poison]
Type = "Debuff"
Icon = "hl_poison"

[Petrifying]
Type = "Debuff"
Icon = "bd_stonecurse"

[Stone]
Type = "Debuff"
Icon = "bd_stonecurse"

[Provoke]
Type = "Debuff"
Icon = "프로보크"

[ProvokeNoAtk]
Type = "Debuff"
Icon = "프로보크"

[Hallucination]
Type = "Debuff"
Icon = "환각"

#----------------------------------
# Player Buffs
#----------------------------------

[PushCart]
Name = "Push Cart"
Type = "Buff"
CanDispel = false
CanDisable = false

[TwoHandQuicken]
Name = "Two-Hand Quicken"
Type = "Buff"
Icon = "투핸드퀴큰"
CanDispel = true
CanDisable = true

[Blessing]
Name = "Blessing"
Type = "Buff"
Icon = "블레싱"
CanDispel = true
CanDisable = true

[IncreaseAgi]
Name = "Increase Agility"
Type = "Buff"
Icon = "민첩성증가"
CanDispel = true
CanDisable = true

[DecreaseAgi]
Name = "Decrease Agility"
Type = "Debuff"
Icon = "민첩성감소"
CanDispel = true
CanDisable = true

[Angelus]
Name = "Angelus"
Type = "Buff"
Icon = "안젤루스"
CanDispel = true
CanDisable = true

[SignumCrusis]
Name = "SignumCrusis"
Type = "Debuff"
Icon = "시그넘크루시스"

[ImproveConcentration]
Name = "Improve Concentration"
Type = "Buff"
Icon = "집중력향상"
CanDispel = true
CanDisable = true

[Endure]
Name = "Endure"
Type = "Buff"
Icon = "인듀어"
CanDispel = true
CanDisable = true

[MagnumBreak]
Name = "Magnum Break"
Type = "Buff"
Icon = "icon02"
CanDispel = true
CanDisable = true

[Pneuma]
Name = "Pneuma"
Type = "Buff"

[SafetyWall]
Name = "Pneuma"
Type = "Buff"

[Hiding]
Name = "Hiding"
Type = "Buff"
Icon = "하이딩"
CanDispel = false
CanDisable = true

[CrazyUproar]
Name = "Crazy Uproar"
Type = "Buff"
Icon = "고성지르기"
CanDispel = true
CanDisable = true

[Cloaking]
Type = "Buff"
Icon = "클로킹"
CanDispel = false
CanDisable = true

[EnergyCoat]
Name = "Energy Coat"
Type = "Buff"
Icon = "에너지코트"
CanDispel = true
CanDisable = true

[Sight]
Type = "Buff"
CanDispel = false
CanDisable = false

[Ruwach]
Type = "Buff"
CanDispel = false
CanDisable = false

[Detoxify]
Name = "Poison Resistance"
Type = "Buff"
Icon = "Detoxify"
CanDispel = true
CanDisable = true

[AdrenalineRush]
Name = "Adrenaline Rush"
Type = "Buff"
Icon = "아드레날린러쉬"
CanDispel = true
CanDisable = true

[AnkleSnare]
[EnchantPoison]
Name = "Enchant Poison"
Type = "Buff"
Icon = "인찬트포이즌"
CanDispel = true
CanDisable = true

[Falcon]
Name = "Falcon"
Type = "Buff"
CanDispel = false
CanDisable = false

[PecoRiding]
Name = "Peco Peco Riding"
Type = "Buff"
Icon = "라이딩"
CanDispel = false
CanDisable = false

[VenomSplasher]
Name = "Venom Splasher"
Type = "Debuff"
CanDispel = false
CanDisable = false


[PoisonReact]
Name = "Poison React"
Type = "Buff"
Icon = "포이즌리액트"
CanDispel = true
CanDisable = true

#----------------------------------
# Priest
#----------------------------------

[Magnificat]
Type = "Buff"
Icon = "마니피캇"
CanDispel = true
CanDisable = true

[Gloria]
Type = "Buff"
Icon = "글로리아"
CanDispel = true
CanDisable = true

[ImpositioManus]
Name = "Impositio Manus"
Type = "Buff"
Icon = "임포시티오마누스"
CanDispel = true
CanDisable = true

[KyrieEleison]
Name = "Kyrie Eleison"
Type = "Buff"
Icon = "기리에엘레이손"
CanDispel = true
CanDisable = true

[Suffragium]
Type = "Buff"
Icon = "수프라기움"
CanDispel = true
CanDisable = true

[LexAeterna]
Type = "Debuff"
Icon = "렉스에테르나"
CanDispel = true
CanDisable = false

[Aspersio]
Type = "Buff"
Icon = "아스페르시오"
CanDispel = true
CanDisable = true

#----------------------------------
# Item Buffs
#----------------------------------

[IncreasedMoveSpeed]
Name = "Movement Speed Up"
Type = "Buff"
Icon = "민첩성증가"
CanDispel = true
CanDisable = true

[IncreasedAttackSpeed]
Name = "Attack Speed Up"
Type = "Buff"
Icon = "공속물약"
CanDispel = true
CanDisable = true

[ElementalConverter]
Name = "Elemental Converter"
Type = "Buff"
CanDispel = true
CanDisable = true

[ElementalConverterFire]
Name = "Elemental Converter (Fire)"
Type = "Buff"
Icon = "weapon_property_fire"
CanDispel = true
CanDisable = true

[ElementalConverterWater]
Name = "Elemental Converter (Water)"
Type = "Buff"
Icon = "weapon_property_water"
CanDispel = true
CanDisable = true

[ElementalConverterWind]
Name = "Elemental Converter (Wind)"
Type = "Buff"
Icon = "weapon_property_wind"
CanDispel = true
CanDisable = true

[ElementalConverterEarth]
Name = "Elemental Converter (Earth)"
Type = "Buff"
Icon = "weapon_property_ground"
CanDispel = true
CanDisable = true

[CursedWater]
Name = "Cursed Water"
Type = "Buff"
Icon = "i_p_dark"
CanDispel = true
CanDisable = true

#----------------------------------
# Monster Status Effects
#----------------------------------

[GuidedAttack]
Name = "Guided Attack"
Type = "Buff"
CanDispel = true
CanDisable = true

[MagicalAttack]
Name = "Magic Weapon"
Type = "Buff"
CanDispel = true
CanDisable = true

[DarkBlessing]
Name = "Dark Blessing"
Type = "Debuff"
Icon = "pharaoh_curse"
CanDispel = false
CanDisable = false

[PowerUp]
Name = "Power Up"
Type = "Buff"
Icon = "icon02"
CanDispel = false
CanDisable = false

[SpeedUp]
Name = "Speed Up"
Type = "Buff"
Icon = "민첩성증가"
CanDispel = true
CanDisable = false

[Vampyrism]
Type = "Buff"
Icon = "icon02"
CanDispel = true
CanDisable = false

#Doom is used to kill monsters after a set period of time
[Doom]
Name = "Doom"
Type = "Debuff"
CanDispel = false
CanDisable = true

[Bulwark]
Name = "Bulwark"
Type = "Buff"
CanDispel = true
CanDisable = true

[Smoking]
Name = "Smoking"
Type = "Debuff"

[Stop]
Name = "Stop"
Icon = "bd_imprison"
Type = "Debuff"
CanDispel = true
CanDisable = false

[StopOwner]
CanDispel = false
CanDisable = false

[Invisible]

[Vulnerability] #for special events
[SpecialTarget] #for special events

#----------------------------------
# Utility Effects
#----------------------------------

[AdminHide]
Name = "Admin Invisibility"
Type = "Buff"
Icon = "하이딩"
CanDisable = true
CanDispel = false

#monsters get this status after a thief steals an item to block further attempts
[StolenFrom]
Name = "Stolen From"
Type = "Debuff"
CanDisable = false
CanDispel = false